#!/bin/bash
#
# Executes a Tomcat startup command and notes the PID

if [ $# -lt 3 ]; then
    echo -n "Usage: $0 pidfile init_log command"
    exit 1
fi
# extract params
pidfile="$1"
logfile="$2"
cmd="$3"
shift 3

# check if we can access pidfile
touch "$pidfile"
if [ ! $? = "0" ]; then
    echo -n "Could not touch pidfile: $pidfile"
    exit 1;
fi

# run command
$cmd $@ >> "$logfile" 2>&1 &
pid=$!
# check that the process is running
# 1sec is not enough
sleep 2
if [ ! -d "/proc/$pid" ]; then
    echo -n "Error, check logfile $logfile"
    exit 1;
fi

# write pid file
echo "$pid" > "$pidfile" 

if [ ! $? = "0" ]; then
    echo -n "Could not write pid to pidfile: $pidfile"
    exit 1;
fi
exit 0 
